# permissions for end users to view testcrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testcrd-viewer-role
rules:
- apiGroups:
  - custom.test.com
  resources:
  - testcrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - custom.test.com
  resources:
  - testcrds/status
  verbs:
  - get
